In [2]:
import ase.io.lammpsdata as io
from ase.visualize import view#
import os
import numpy as np
import ase.io as ase
cell_size = 14.1328

tol = cell_size/8.0
cell = cell_size/(8.0)


1.7666


In [3]:
def cell_cutter(initial,final,stepafter):

    atoms = io.read_lammps_data(initial,style="atomic")
    nextatoms = io.read_lammps_data(final,style="atomic")
    afteratoms = io.read_lammps_data(stepafter,style="atomic")

    diff = atoms.get_positions()-nextatoms.get_positions()
    store = 0
    entry = []
    for i in diff:
        current = np.linalg.norm(i)
        if current > 1.0:
            store = i
            entry.append(i)
            
    atom_pos =atoms.get_positions()[np.where(store==diff)[0][0]]
    afteratom_pos =afteratoms.get_positions()[np.where(store==diff)[0][0]]
    #pos_diff = np.abs(afteratom_pos-atom_pos)

    return  len(entry),nextatoms.get_positions()[np.where(store==diff)[0][0]],atom_pos,afteratom_pos#pos_diff
    


In [4]:
noSteps = 500

vac_pos = np.zeros((noSteps,3))
pos = np.zeros((noSteps,3))
pos_after = np.zeros((noSteps,3))
no_atoms = []
for i in range(noSteps-2):
    initial = "steps/step{}.txt".format(i)
    final = "steps/step{}.txt".format(i+1)
    after = "steps/step{}.txt".format(i+2)
    res = cell_cutter(initial,final,after)
    vac_pos[i,:] = res[1]
    no_atoms.append(res[0])
    pos[i,:] = res[2]
    pos_after[i,:] = res[3]
    

In [6]:
# Code identifies end of flickers, is broken by flickers that are a cycle >2

prev = np.array([-1,-1,-1])
minustwo = np.array([-1,-1,-1])
minus3 = np.array([-1,-1,-1])
flickers = []
index = 0
p=0
for i in vac_pos:#//cell:
    #print(i,minustwo)
    #print(i)
    arr = [index,index-1,index-2,index-3]
    if np.all(np.abs(prev-minus3)<tol) and np.any(np.abs(minustwo-i)>tol) and \
    not(np.any(np.isin(np.where(np.array(no_atoms)>1)[0],arr))) and \
    index!=4 and index!=0 \
    and np.all(pos[index-3]-pos_after[index-3]<tol):
        
        
        print(minus3,minustwo,prev,np.around(i,decimals=1),index,index-1,index-2,index-3)
        flickers.append([index,index-1,index-2,index-3])
    index +=1
    minus3=minustwo
    minustwo = prev
    prev = np.around(i,decimals=1)
#print(vac_pos[45:50])

[21.9  7.9  8.2] [20.4  8.   9.5] [22.1  8.1  7.8] [22.1  9.8  6.4] 60 59 58 57
1 0.1
[22.1  8.1  7.8] [22.1  9.8  6.4] [21.9  7.9  8.2] [20.4  8.   9.5] 62 61 60 59
2 0.2
[20.2  8.1 13.2] [20.2  9.5 11.5] [20.2  8.1 13.2] [18.5  9.6 13.3] 70 69 68 67
3 0.0
[20.2  8.1 13.2] [18.5  9.6 13.3] [20.2  8.  13.2] [18.3  6.4 13.1] 72 71 70 69
4 0.3
[18.4  9.8 13.4] [18.4 11.4  0.8] [18.5  9.5 13.1] [18.3  8.1 11.5] 77 76 75 74
5 0.3
[18.5  9.5 13.1] [18.3  8.1 11.5] [18.4  9.8 13.4] [18.4 11.4  0.8] 85 84 83 82
6 0.0
[18.4 11.4  0.8] [18.4  9.8 13.4] [18.4 11.5  0.9] [18.5 13.2  2.4] 88 87 86 85
7 -0.2
[27.4  2.7  8.1] [25.9  2.6  9.6] [27.3  2.7  7.7] [25.9  2.6  6.2] 112 111 110 109
8 0.3
[27.3  2.7  7.7] [25.9  2.6  6.2] [27.4  2.7  8.1] [25.9  2.6  9.6] 116 115 114 113
9 0.1
[27.4  2.7  8.1] [25.9  2.6  9.6] [27.3  2.7  7.7] [25.9  2.6  6.2] 118 117 116 115
10 0.3
[27.3  2.7  7.7] [25.9  2.6  6.2] [27.4  2.7  8.1] [25.9  2.6  9.6] 120 119 118 117
11 0.1
[27.4  2.7  8.1] [25.9  2.6  9.6] [

 [18.3  6.2  9.5] [16.8  6.   7.6] [16.7  4.5  6.3] 382 381 380 379
41 0.2
[16.8  6.   7.6] [16.7  4.5  6.3] [17.   6.2  8. ] [18.3  6.2  9.5] 384 383 382 381
42 0.1
[17.   6.2  8. ] [18.3  6.2  9.5] [16.7  6.2  8. ] [15.1  6.2  9.5] 392 391 390 389
43 0.3
[16.7  6.2  8. ] [15.1  6.2  9.5] [17.   6.2  8. ] [18.3  6.2  9.5] 394 393 392 391
44 0.1
[17.   6.2  8. ] [18.3  6.2  9.5] [16.8  6.   7.6] [16.7  4.5  6.3] 420 419 418 417
45 0.2
[16.8  6.   7.6] [16.7  4.5  6.3] [17.   6.2  8. ] [18.3  6.2  9.5] 422 421 420 419
46 0.1
[17.   6.2  8. ] [18.3  6.2  9.5] [16.8  6.   7.6] [16.7  4.5  6.3] 424 423 422 421
47 0.2
[16.8  6.   7.6] [16.7  4.5  6.3] [17.   6.2  8. ] [18.3  6.2  9.5] 426 425 424 423
48 0.1
[17.   6.2  8. ] [18.3  6.2  9.5] [16.8  6.   7.6] [16.7  4.5  6.3] 434 433 432 431
49 0.2
[16.8  6.   7.6] [16.7  4.5  6.3] [17.   6.2  8. ] [18.3  6.2  9.5] 436 435 434 433
50 0.1
[17.   6.2  8. ] [18.3  6.2  9.5] [16.8  6.   7.6] [16.7  4.5  6.3] 446 445 444 443
51 0.2
[16.8  6.   7.6